Master
htmlacademy-htmlcss/2223581-sedona-38 pull request #2
Opened 2023-09-24 21:38 UTC by MariaGuzenko

Добавление разметки

2023-09-27 07:10 UTC, jumile requested changes

2023-09-27 07:10 UTC, jumile commented on index.html
> +        <a class="logo" href="">
href="#"

2023-09-27 07:10 UTC, jumile commented on index.html
> +        <ul class="navigation list">
navigation-list

2023-09-27 07:10 UTC, jumile commented on index.html
> +            <a class="navigation-link link" href="about.html">О Седоне</a>
href="#"

2023-09-27 07:10 UTC, jumile commented on index.html
> +            </label>
label class="visually-hidden" for="newsletter-email" Ваш e-mail   /label

2023-09-27 07:10 UTC, jumile commented on index.html
> +          <h1><span class="visually-hidden">Добро пожаловать в великолепную Седону</span></h1>
div и span - лишние обертки

2023-09-27 07:10 UTC, jumile commented on index.html
> +      <div class="page-footer-container">
Лишняя обертка

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +        <a class="logo" href="">
адрес добавить

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +        <ul class="navigation list">
2 класса или 1?

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +              <a class="breadcrumbs-link breadcrumbs-link-home" href="index.html">Главная</a>
Текст здесь не должно быть видно.

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +              <a class="breadcrumbs-link" href="catalog.html">Гостиницы</a>
Нужна ли здесь ссылка?

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +            <div class="catalog-filter-container-left">
лишняя обертка?

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +            <div class="catalog-filter-container-right">
Лишняя обертка?

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +          <h2 class="visually-hidden"> Список гостиниц с фильтрами</h2>
Просто фильтры.

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +<button class="card-grid-toggle card-grid-toggle-tile card-grid-toggle-current link" type="button">
button / a

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +<ul class="hotel list">
2 класса или 1?

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +  <span class="frame-hotel">Гос9тиница</span>
опечатка

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +  <span class="rating-value">8,5</span>
лишняя обертка?

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +  <p class="frame-hotel-price">
Обертки для "парных" элементов необязательны.

2023-09-27 07:10 UTC, jumile commented on catalog.html
> +  <div class="pagination-inner">
зачем обертка?

2023-09-27 09:35 UTC, MariaGuzenko commented on catalog.html
> +        <a class="logo" href="">
> адрес добавить

исправлено

2023-09-27 09:35 UTC, MariaGuzenko commented on catalog.html
> +        <ul class="navigation list">
исправлено на navigation-list

2023-09-27 09:40 UTC, MariaGuzenko commented on index.html
> +        <a class="logo" href="">
исправлено

2023-09-27 09:40 UTC, MariaGuzenko commented on index.html
> +        <ul class="navigation list">
исправлено

2023-09-27 09:42 UTC, MariaGuzenko commented on index.html
> +          <h1><span class="visually-hidden">Добро пожаловать в великолепную Седону</span></h1>
убрала

2023-09-27 09:44 UTC, MariaGuzenko commented on index.html
> +      <div class="page-footer-container">
убрала

2023-09-27 10:14 UTC, MariaGuzenko commented on catalog.html
> +              <a class="breadcrumbs-link breadcrumbs-link-home" href="index.html">Главная</a>
добавила стиль <span class="visually-hidden">Избранное</span>

2023-09-27 18:15 UTC, MariaGuzenko commented on catalog.html
> +              <a class="breadcrumbs-link breadcrumbs-link-home" href="index.html">Главная</a>
исправила

2023-09-27 18:16 UTC, MariaGuzenko commented on catalog.html
> +              <a class="breadcrumbs-link" href="catalog.html">Гостиницы</a>
убрала, правильно ли сделала?

2023-09-27 18:16 UTC, MariaGuzenko commented on catalog.html
> +          <h2 class="visually-hidden"> Список гостиниц с фильтрами</h2>
исправила

2023-09-27 18:37 UTC, MariaGuzenko commented on catalog.html
> +            <div class="catalog-filter-container-left">
удалила

2023-09-27 19:03 UTC, MariaGuzenko commented on catalog.html
> +            <div class="catalog-filter-container-right">
удалила

2023-09-27 19:35 UTC, MariaGuzenko commented on catalog.html
> +<button class="card-grid-toggle card-grid-toggle-tile card-grid-toggle-current link" type="button">
исправила на a (ссылку) т.к. носит характер навигации на странице

2023-09-27 19:35 UTC, MariaGuzenko commented on catalog.html
> +<ul class="hotel list">
1 класс, исправлено

2023-09-27 19:38 UTC, MariaGuzenko commented on catalog.html
> +  <span class="frame-hotel">Гос9тиница</span>
исправила

2023-09-27 19:40 UTC, MariaGuzenko commented on catalog.html
> +  <div class="pagination-inner">
убрала

2023-09-28 08:47 UTC, jumile commented on catalog.html
> +              <a class="breadcrumbs-link" href="catalog.html">Гостиницы</a>
Да, вполне.

2023-09-28 08:49 UTC, jumile approved these changes
Да, все исправления верные. Можно принимать задание.

2023-09-28 12:07 UTC, merged